export const textosPt = {
  "painel": "Ateliê CatSuite",
  "descricaoPainel": "Do primeiro comando ao pacote assinado. Tudo local, com acesso e identidade visíveis.",
  "criarProjeto": "Criar extensão",
  "validarProjeto": "Validar projeto",
  "simularProjeto": "Testar com fixture local",
  "empacotarProjeto": "Gerar .catplug assinado",
  "aplicarEstilo": "Aplicar estilo CatSuite",
  "restaurarEstilo": "Restaurar estilo anterior",
  "inspecionarPacote": "Inspecionar arquivo CatSuite",
  "atualizarHashes": "Atualizar hashes do manifesto",
  "inserirRecurso": "Inserir recurso do SDK",
  "criarFluxo": "Criar fluxo de exemplo",
  "verIdentidade": "Ver identidade de assinatura",
  "exportarIdentidade": "Exportar backup protegido da identidade",
  "importarIdentidade": "Restaurar identidade de backup",
  "escolherIdioma": "Escolher idioma",
  "abrirConfiguracoes": "Abrir opções do CatSuite Studio",
  "confiarAutor": "Reconhecer autor deste pacote",
  "removerAutor": "Remover autor reconhecido",
  "abrirCodigo": "Abrir código",
  "atualizar": "Atualizar",
  "projetos": "Projetos CatSuite",
  "recursos": "Recursos do SDK",
  "nenhumProjeto": "Nenhum projeto CatSuite aberto",
  "escolherProjeto": "Escolha o projeto CatSuite",
  "escolherModelo": "O que sua extensão deve fazer?",
  "nomeProjeto": "Nome da extensão no idioma atual",
  "nomeSecundario": "Nome no idioma secundário (opcional)",
  "autorProjeto": "Autor público do pacote",
  "idProjeto": "Identidade permanente, como minha.extensao",
  "pastaProjeto": "Pasta para o novo projeto",
  "nomeInvalido": "Use de 1 a 120 caracteres, sem controles.",
  "idInvalido": "Use letras minúsculas, números, pontos e hífens; de 3 a 64 caracteres.",
  "pastaExiste": "A pasta já existe. Escolha outro nome.",
  "projetoCriado": "Projeto criado. O pacote começa desativado no CatSuite.",
  "abrirPasta": "Abrir pasta",
  "workspaceNecessario": "Abra uma pasta de projeto CatSuite para continuar.",
  "confiancaNecessaria": "Confie neste workspace no VS Code para criar, simular ou assinar. A inspeção e o auxílio ao código continuam disponíveis.",
  "virtualNaoSuportado": "Esta operação requer uma pasta local ou remota com sistema de arquivos.",
  "salvarEdicoes": "Salve as alterações do projeto antes de validar os arquivos e gerar uma entrega.",
  "salvar": "Salvar",
  "cancelar": "Cancelar",
  "confirmar": "Confirmar",
  "validacaoPronta": "Validação concluída: {erros} erros e {avisos} avisos.",
  "preparando": "Preparando ambiente local…",
  "simulando": "Executando fixture no QuickJS…",
  "simulacaoPronta": "Prévia concluída. Nenhuma request externa foi enviada.",
  "empacotando": "Validando, assinando e preparando o pacote…",
  "exportacaoFormato": "Como deseja salvar o pacote?",
  "pacoteAssinado": "Assinado",
  "pacoteProtegido": "Assinado + senha",
  "senhaArquivo": "Senha do arquivo (12 a 1.024 bytes UTF-8)",
  "confirmarSenha": "Repita a senha",
  "senhasDiferentes": "As senhas não correspondem.",
  "pacotePronto": "Pacote validado e assinado: {arquivo}",
  "protegido": "Conteúdo protegido",
  "abrirProtegido": "Abrir com senha",
  "protegidoAjuda": "Nome, código e metadados privados não são exibidos sem a senha.",
  "assinaturaValida": "Assinatura válida",
  "assinaturaAusente": "Sem assinatura",
  "autorReconhecido": "Autor reconhecido neste VS Code",
  "autorNaoReconhecido": "Chave ainda não reconhecida",
  "confiarAviso": "Reconhecer a impressão digital {impressao}? Uma assinatura válida comprova integridade e posse da chave, não a segurança do código.",
  "identidadeCriada": "Identidade Ed25519 protegida pelo armazenamento de segredos do VS Code.",
  "identidadeAusente": "Nenhuma identidade criada. Ela será gerada ao assinar o primeiro pacote.",
  "backupAviso": "O backup contém sua chave privada e será protegido com senha. Guarde-o fora do projeto público.",
  "backupPronto": "Backup protegido salvo.",
  "restaurarAviso": "Substituir a identidade atual pela identidade deste backup?",
  "identidadeRestaurada": "Identidade restaurada.",
  "temaCyber": "CatSuite Cyber",
  "temaConforto": "CatSuite Conforto",
  "estiloEscolher": "Escolha a intensidade do estilo",
  "temaExplicacao": "Cores do editor e ícones serão alterados somente após sua escolha.",
  "temaRestaurado": "Estilo anterior restaurado.",
  "temaNaoSalvo": "Nenhum estilo anterior foi salvo.",
  "temaAtualizado": "Estilo CatSuite aplicado.",
  "idiomaSistema": "Seguir o VS Code",
  "idiomaPt": "Português do Brasil",
  "idiomaEn": "Inglês",
  "idiomaAtualizado": "Idioma atualizado.",
  "modelo.painel": "Painel e comandos",
  "modelo.analise": "Análise de tráfego",
  "modelo.headers": "Modificação de headers",
  "modelo.fluxo": "Etapa de fluxo",
  "modelo.parser": "Parser JSON",
  "modeloAjuda.painel": "Aba própria, botão e contador persistente. Sem rede.",
  "modeloAjuda.analise": "Observa uma response e adiciona um achado informativo.",
  "modeloAjuda.headers": "Altera um header de GET/HEAD dentro do escopo.",
  "modeloAjuda.fluxo": "Recebe HTTP e produz uma análise tipada com checkpoint.",
  "modeloAjuda.parser": "Converte corpo JSON completo em dados de análise.",
  "validacoes": "Verificações",
  "permissoes": "Permissões solicitadas",
  "destinos": "Destinos de tráfego",
  "arquivos": "Arquivos e integridade",
  "assinatura": "Identidade e assinatura",
  "previa": "Laboratório de prévia",
  "previaAjuda": "Fixture local. HTTP, APIs externas, Bridge e Repetir são simulados; TLS, biometria e o transporte Android exigem teste no CatSuite.",
  "fluxo": "Mapa de fluxo",
  "etapas": "Etapas",
  "conexoes": "Conexões",
  "semEnvios": "Sem tráfego externo",
  "somenteLeitura": "Inspeção sem executar código",
  "rascunhoEtiqueta": "Rascunho",
  "confiavelEtiqueta": "Workspace confiável",
  "restritoEtiqueta": "Modo restrito",
  "errosEtiqueta": "Erros",
  "avisosEtiqueta": "Avisos",
  "abrirManifesto": "Abrir manifesto",
  "comandos": "Comandos",
  "abas": "Abas",
  "achados": "Achados",
  "artefatos": "Artefatos",
  "registros": "Registros",
  "mensagem": "Mensagem HTTP",
  "duracao": "Duração",
  "copiarImpressao": "Copiar impressão digital",
  "copiado": "Copiado.",
  "copiarResultado": "Copiar resumo com dados sensíveis ocultos",
  "semResultados": "Nenhum resultado nesta seção.",
  "statusPronto": "Projeto pronto para revisar",
  "retomar": "Revalidar",
  "arquivoAtual": "Arquivo atual",
  "etapaCriar": "Criar",
  "etapaValidar": "Validar",
  "etapaTestar": "Testar",
  "etapaAssinar": "Assinar",
  "falhaGenerica": "Não foi possível concluir a operação.",
  "operacaoInvalida": "Operação não reconhecida.",
  "jsonInvalido": "JSON estrito inválido. Comentários e vírgulas finais não são aceitos no pacote.",
  "chaveDuplicada": "Chave JSON duplicada: {chave}.",
  "chaveReservada": "Chave reservada: {chave}.",
  "numeroInseguro": "Número não finito ou inteiro sem precisão segura.",
  "profundidade": "Estrutura excede a profundidade permitida.",
  "destinoInvalido": "Destino inválido ou ambíguo: {destino}.",
  "destinoAmbiguo": "Representação ambígua de IP: {destino}.",
  "versaoIncompativel": "Versão de formato, SDK ou API incompatível.",
  "identidadeInvalida": "Identidade de extensão inválida.",
  "campoObrigatorio": "Campo obrigatório: {campo}.",
  "traducaoAusente": "Tradução obrigatória ausente: {idioma}.",
  "entradaInvalida": "A entrada deve apontar para um JavaScript incluído no projeto.",
  "permissaoInvalida": "Permissão desconhecida ou duplicada.",
  "revisaoInvalida": "A revisão e a linhagem devem usar UUID válido.",
  "hashInvalido": "Integridade inválida: arquivo ausente, hash incorreto ou arquivo extra.",
  "assinaturaInvalida": "Assinatura inválida. O conteúdo não deve ser instalado.",
  "configuracaoInvalida": "Definição de configuração incompatível.",
  "tamanho": "Tamanho ou quota excedido.",
  "senhaLimite": "Senha fora do limite permitido.",
  "parametrosCripto": "Cabeçalho criptográfico ou parâmetros de derivação inválidos.",
  "senhaIncorreta": "Senha incorreta ou arquivo adulterado.",
  "sintaxe": "Sintaxe JavaScript inválida: {detalhe}.",
  "apiIndisponivel": "{api} não está disponível no runtime CatSuite.",
  "apiDesconhecida": "API não reconhecida pelo SDK: {api}.",
  "permissaoAusente": "{api} exige a permissão {permissao}.",
  "handlerSincrono": "Handlers de alteração devem ser síncronos e não executar operações assíncronas.",
  "apiDinamica": "Acesso dinâmico: revise manualmente a API e suas permissões.",
  "segredoEncontrado": "Possível chave privada ou credencial pública encontrada no código.",
  "fluxoInvalido": "Fluxo sem definição válida de blocos e conexões.",
  "blocoDuplicado": "Identificadores de blocos duplicados.",
  "blocoInvalido": "Bloco ou contrato de artefatos inválido.",
  "conexaoInvalida": "Conexão inválida, duplicada ou condição inadequada.",
  "tipoIncompativel": "Artefatos incompatíveis entre {origem} e {destino}.",
  "ciclo": "O fluxo contém um ciclo.",
  "semAssinatura": "Arquivo sem assinatura: revisão e assinatura são necessárias antes da distribuição.",
  "caminhoInvalido": "Caminho indevido ou link simbólico: {caminho}.",
  "projetoInvalido": "Configuração catsuite.projeto.json inválida.",
  "arquivoPrivado": "Arquivo privado não pode entrar no pacote: {arquivo}.",
  "hashDesatualizado": "Hash desatualizado. Será recalculado ao empacotar.",
  "rascunho": "Manifesto em rascunho. Hashes e assinatura serão gerados ao empacotar.",
  "pacoteInvalido": "Arquivo ZIP inválido ou corrompido.",
  "arquivoProtegido": "Arquivo protegido requer senha.",
  "manifestoAusente": "manifest.json ausente.",
  "validacaoFalhou": "Corrija os erros de validação antes de continuar.",
  "execucaoFalhou": "Prévia interrompida: {detalhe}.",
  "tempoEsgotado": "Prazo de execução excedido.",
  "promessaPendente": "Promessa não concluída na fixture local.",
  "cancelado": "Operação cancelada.",
  "recursoPermissao": "Requer permissão: {permissao}.",
  "recursoSemPermissao": "Disponível sem permissão adicional.",
  "gerarDiagnostico": "Gerar manifesto e SDK em uma pasta separada.",
  "versaoSdk": "SDK 1.4 · API v1",
  "restricoes": "A inspeção não executa pacotes. O empacotamento usa somente a lista explícita de arquivos.",
  "nenhumErro": "Nenhum erro encontrado nesta verificação.",
  "backupLocal": "Não salve a chave no workspace público.",
  "fixtureInvalida": "Fixture deve conter uma mensagem HTTP válida.",
  "fixtureAusente": "Fixture local não encontrada.",
  "revisao": "Revisão",
  "semDestino": "Nenhum destino de rede solicitado.",
  "adicionarPermissao": "Adicionar {permissao} ao manifesto",
  "somenteWorkspace": "Somente neste workspace",
  "todoEditor": "Em todo o VS Code",
  "eventos": "Eventos observados",
  "desenvolvimentoPlugins": "Desenvolvimento de plugins",
  "novoScript": "Novo script CatPlug",
  "abrirScript": "Abrir script no editor",
  "editarPacote": "Criar cópia editável do pacote",
  "aplicarIcones": "Aplicar ícones CatSuite",
  "sugestoesGlobais": "Mostrar sugestões de cat. e modelos catplug em qualquer formato, inclusive arquivos sem projeto.",
  "scriptCatPlug": "Script de plugin CatSuite",
  "scriptModelo": "Modelo editável de plugin; insere código neste arquivo.",
  "scriptPacoteAjuda": "Scripts abrem no editor. Pacotes assinados podem ser convertidos em uma cópia editável.",
  "scriptCopiado": "Cópia editável criada. O pacote original foi preservado; a revisão é um rascunho.",
  "editarPacoteAviso": "Será criada uma pasta de fontes para editar o JavaScript. O pacote original não será sobrescrito e nenhum código será executado.",
  "logoCatSuite": "Logo do CatSuite Studio",
  "script": "Script",
  "iconeAtualizado": "Ícones CatSuite aplicados.",
  "scriptFormato": "Arquivo textual de desenvolvimento. Para importar no aplicativo, gere um pacote assinado no projeto."
};
export const textosEn: Record<string,string> = {
  "painel": "CatSuite Atelier",
  "descricaoPainel": "From the first command to the signed package. Local tools with visible access and identity.",
  "criarProjeto": "Create extension",
  "validarProjeto": "Validate project",
  "simularProjeto": "Test with a local fixture",
  "empacotarProjeto": "Build signed .catplug",
  "aplicarEstilo": "Apply CatSuite style",
  "restaurarEstilo": "Restore previous style",
  "inspecionarPacote": "Inspect CatSuite file",
  "atualizarHashes": "Update manifest hashes",
  "inserirRecurso": "Insert SDK feature",
  "criarFluxo": "Create example workflow",
  "verIdentidade": "Show signing identity",
  "exportarIdentidade": "Export protected identity backup",
  "importarIdentidade": "Restore identity from backup",
  "escolherIdioma": "Choose language",
  "abrirConfiguracoes": "Open CatSuite Studio settings",
  "confiarAutor": "Recognize this package author",
  "removerAutor": "Remove recognized author",
  "abrirCodigo": "Open code",
  "atualizar": "Refresh",
  "projetos": "CatSuite projects",
  "recursos": "SDK features",
  "nenhumProjeto": "No CatSuite project open",
  "escolherProjeto": "Choose a CatSuite project",
  "escolherModelo": "What should your extension do?",
  "nomeProjeto": "Extension name in the current language",
  "nomeSecundario": "Name in the secondary language (optional)",
  "autorProjeto": "Public package author",
  "idProjeto": "Permanent identity, such as my.extension",
  "pastaProjeto": "Folder for the new project",
  "nomeInvalido": "Use 1–120 characters without control characters.",
  "idInvalido": "Use lowercase letters, numbers, dots and hyphens; 3–64 characters.",
  "pastaExiste": "The folder already exists. Choose another name.",
  "projetoCriado": "Project created. The package starts disabled in CatSuite.",
  "abrirPasta": "Open folder",
  "workspaceNecessario": "Open a CatSuite project folder to continue.",
  "confiancaNecessaria": "Trust this workspace in VS Code to create, simulate or sign. Inspection and code assistance remain available.",
  "virtualNaoSuportado": "This operation requires a local or remote filesystem folder.",
  "salvarEdicoes": "Save project edits before validating files or building a deliverable.",
  "salvar": "Save",
  "cancelar": "Cancel",
  "confirmar": "Confirm",
  "validacaoPronta": "Validation complete: {erros} errors and {avisos} warnings.",
  "preparando": "Preparing local environment…",
  "simulando": "Running fixture in QuickJS…",
  "simulacaoPronta": "Preview complete. No external request was sent.",
  "empacotando": "Validating, signing and preparing the package…",
  "exportacaoFormato": "How would you like to save the package?",
  "pacoteAssinado": "Signed",
  "pacoteProtegido": "Signed + password",
  "senhaArquivo": "File password (12–1,024 UTF-8 bytes)",
  "confirmarSenha": "Repeat password",
  "senhasDiferentes": "Passwords do not match.",
  "pacotePronto": "Package validated and signed: {arquivo}",
  "protegido": "Protected content",
  "abrirProtegido": "Open with password",
  "protegidoAjuda": "Name, code and private metadata are hidden until unlocked.",
  "assinaturaValida": "Valid signature",
  "assinaturaAusente": "Unsigned",
  "autorReconhecido": "Author recognized in this VS Code",
  "autorNaoReconhecido": "Key not yet recognized",
  "confiarAviso": "Recognize fingerprint {impressao}? A valid signature proves integrity and key possession, not code safety.",
  "identidadeCriada": "Ed25519 identity protected by VS Code secret storage.",
  "identidadeAusente": "No identity created yet. One will be generated when signing the first package.",
  "backupAviso": "The backup contains your private key and will be password-protected. Store it outside the public project.",
  "backupPronto": "Protected backup saved.",
  "restaurarAviso": "Replace the current identity with this backup identity?",
  "identidadeRestaurada": "Identity restored.",
  "temaCyber": "CatSuite Cyber",
  "temaConforto": "CatSuite Comfort",
  "estiloEscolher": "Choose the style intensity",
  "temaExplicacao": "Editor colors and icons change only after your selection.",
  "temaRestaurado": "Previous style restored.",
  "temaNaoSalvo": "No previous style has been saved.",
  "temaAtualizado": "CatSuite style applied.",
  "idiomaSistema": "Follow VS Code",
  "idiomaPt": "Brazilian Portuguese",
  "idiomaEn": "English",
  "idiomaAtualizado": "Language updated.",
  "modelo.painel": "Panel and commands",
  "modelo.analise": "Traffic analysis",
  "modelo.headers": "Header modification",
  "modelo.fluxo": "Workflow step",
  "modelo.parser": "JSON parser",
  "modeloAjuda.painel": "Custom tab, button and persisted counter. No network.",
  "modeloAjuda.analise": "Observes a response and adds an informational finding.",
  "modeloAjuda.headers": "Modifies a GET/HEAD header within scope.",
  "modeloAjuda.fluxo": "Receives HTTP and produces typed analysis with a checkpoint.",
  "modeloAjuda.parser": "Converts a complete JSON body into analysis data.",
  "validacoes": "Checks",
  "permissoes": "Requested permissions",
  "destinos": "Traffic destinations",
  "arquivos": "Files and integrity",
  "assinatura": "Identity and signature",
  "previa": "Preview laboratory",
  "previaAjuda": "Local fixture. HTTP, external APIs, Bridge and Repeater are mocked; TLS, biometrics and Android transport require testing in CatSuite.",
  "fluxo": "Workflow map",
  "etapas": "Steps",
  "conexoes": "Connections",
  "semEnvios": "No external traffic",
  "somenteLeitura": "Inspection without code execution",
  "rascunhoEtiqueta": "Draft",
  "confiavelEtiqueta": "Trusted workspace",
  "restritoEtiqueta": "Restricted mode",
  "errosEtiqueta": "Errors",
  "avisosEtiqueta": "Warnings",
  "abrirManifesto": "Open manifest",
  "comandos": "Commands",
  "abas": "Tabs",
  "achados": "Findings",
  "artefatos": "Artifacts",
  "registros": "Logs",
  "mensagem": "HTTP message",
  "duracao": "Duration",
  "copiarImpressao": "Copy fingerprint",
  "copiado": "Copied.",
  "copiarResultado": "Copy summary with sensitive data redacted",
  "semResultados": "No results in this section.",
  "statusPronto": "Project ready for review",
  "retomar": "Revalidate",
  "arquivoAtual": "Current file",
  "etapaCriar": "Create",
  "etapaValidar": "Validate",
  "etapaTestar": "Test",
  "etapaAssinar": "Sign",
  "falhaGenerica": "The operation could not be completed.",
  "operacaoInvalida": "Unrecognized operation.",
  "jsonInvalido": "Invalid strict JSON. Package files do not allow comments or trailing commas.",
  "chaveDuplicada": "Duplicate JSON key: {chave}.",
  "chaveReservada": "Reserved key: {chave}.",
  "numeroInseguro": "Non-finite number or integer outside safe precision.",
  "profundidade": "Structure exceeds the allowed depth.",
  "destinoInvalido": "Invalid or ambiguous destination: {destino}.",
  "destinoAmbiguo": "Ambiguous IP representation: {destino}.",
  "versaoIncompativel": "Incompatible format, SDK or API version.",
  "identidadeInvalida": "Invalid extension identity.",
  "campoObrigatorio": "Required field: {campo}.",
  "traducaoAusente": "Missing required translation: {idioma}.",
  "entradaInvalida": "Entry must point to a JavaScript file included in the project.",
  "permissaoInvalida": "Unknown or duplicate permission.",
  "revisaoInvalida": "Revision and lineage must use valid UUIDs.",
  "hashInvalido": "Invalid integrity: missing file, incorrect hash or extra file.",
  "assinaturaInvalida": "Invalid signature. Content should not be installed.",
  "configuracaoInvalida": "Incompatible configuration definition.",
  "tamanho": "Size or quota exceeded.",
  "senhaLimite": "Password outside the allowed limits.",
  "parametrosCripto": "Invalid cryptographic header or derivation parameters.",
  "senhaIncorreta": "Incorrect password or tampered file.",
  "sintaxe": "Invalid JavaScript syntax: {detalhe}.",
  "apiIndisponivel": "{api} is not available in the CatSuite runtime.",
  "apiDesconhecida": "API not recognized by the SDK: {api}.",
  "permissaoAusente": "{api} requires permission {permissao}.",
  "handlerSincrono": "Modification handlers must be synchronous and cannot perform asynchronous operations.",
  "apiDinamica": "Dynamic access: manually review the API and its permissions.",
  "segredoEncontrado": "Possible private key or published credential found in code.",
  "fluxoInvalido": "Workflow lacks valid blocks and connections.",
  "blocoDuplicado": "Duplicate block identifiers.",
  "blocoInvalido": "Invalid block or artifact contract.",
  "conexaoInvalida": "Invalid or duplicate connection, or inappropriate condition.",
  "tipoIncompativel": "Incompatible artifacts between {origem} and {destino}.",
  "ciclo": "Workflow contains a cycle.",
  "semAssinatura": "Unsigned file: review and signing are required before distribution.",
  "caminhoInvalido": "Unsafe path or symbolic link: {caminho}.",
  "projetoInvalido": "Invalid catsuite.projeto.json configuration.",
  "arquivoPrivado": "Private file cannot be included in the package: {arquivo}.",
  "hashDesatualizado": "Outdated hash. It will be recalculated when packaging.",
  "rascunho": "Draft manifest. Hashes and signature are generated when packaging.",
  "pacoteInvalido": "Invalid or corrupt ZIP file.",
  "arquivoProtegido": "Protected file requires a password.",
  "manifestoAusente": "Missing manifest.json.",
  "validacaoFalhou": "Fix validation errors before continuing.",
  "execucaoFalhou": "Preview interrupted: {detalhe}.",
  "tempoEsgotado": "Execution deadline exceeded.",
  "promessaPendente": "Promise did not complete in the local fixture.",
  "cancelado": "Operation canceled.",
  "recursoPermissao": "Requires permission: {permissao}.",
  "recursoSemPermissao": "Available without additional permission.",
  "gerarDiagnostico": "Generate manifest and SDK in a separate folder.",
  "versaoSdk": "SDK 1.4 · API v1",
  "restricoes": "Inspection does not execute packages. Packaging uses only the explicit file allowlist.",
  "nenhumErro": "No errors found in this check.",
  "backupLocal": "Do not save the key in the public workspace.",
  "fixtureInvalida": "Fixture must contain a valid HTTP message.",
  "fixtureAusente": "Local fixture was not found.",
  "revisao": "Revision",
  "semDestino": "No network destinations requested.",
  "adicionarPermissao": "Add {permissao} to manifest",
  "somenteWorkspace": "Only in this workspace",
  "todoEditor": "Across VS Code",
  "eventos": "Observed events",
  "desenvolvimentoPlugins": "Plugin development",
  "novoScript": "New CatPlug script",
  "abrirScript": "Open script in editor",
  "editarPacote": "Create editable package copy",
  "aplicarIcones": "Apply CatSuite file icons",
  "sugestoesGlobais": "Show cat. suggestions and catplug templates in any format, including files outside projects.",
  "scriptCatPlug": "CatSuite plugin script",
  "scriptModelo": "Editable plugin template; inserts code into this file.",
  "scriptPacoteAjuda": "Scripts open in the editor. Signed packages can be converted into an editable copy.",
  "scriptCopiado": "Editable copy created. The original package was preserved; the revision is a draft.",
  "editarPacoteAviso": "A source folder will be created for JavaScript editing. The original package will not be overwritten and no code will run.",
  "logoCatSuite": "CatSuite Studio logo",
  "script": "Script",
  "iconeAtualizado": "CatSuite file icons applied.",
  "scriptFormato": "Development text file. To import into the app, build a signed package from the project."
};
