(() => {
  const vscode = typeof acquireVsCodeApi === 'function' ? acquireVsCodeApi() : { postMessage() {} };
  const app = document.getElementById('app'); let dicionario = {}; let idioma = 'pt-BR';
  const texto = (chave, args = {}) => (dicionario[chave] || chave).replace(/\{([^}]+)\}/g, (_, nome) => String(args[nome] ?? ''));
  const local = valor => typeof valor === 'string' ? valor : valor?.[idioma] || valor?.['pt-BR'] || valor?.en || '';
  const elemento = (nome, classe, valor) => { const el = document.createElement(nome); if (classe) el.className = classe; if (valor !== undefined) el.textContent = String(valor); return el; };
  const botao = (chave, primario = false) => { const b = elemento('button', primario ? 'primario' : '', texto(chave)); b.type = 'button'; b.addEventListener('click', () => vscode.postMessage({ tipo: 'acao', acao: chave })); return b; };
  function secao(titulo) { const caixa = elemento('section', 'secao'); caixa.append(elemento('h2', '', texto(titulo))); const conteudo = elemento('div', 'conteudo'); caixa.append(conteudo); app.append(caixa); return conteudo; }
  function json(titulo, valor, pai) { const d = elemento('details'); d.append(elemento('summary', '', titulo)); d.append(elemento('pre', '', JSON.stringify(valor, null, 2))); pai.append(d); }
  function lista(titulo, itens) { const c = secao(titulo); const ul = elemento('ul', 'lista'); for (const item of itens || []) ul.append(elemento('li', '', item)); if (!itens?.length) ul.append(elemento('li', 'ajuda', texto('semResultados'))); c.append(ul); }
  function problemas(itens) { const c = secao('validacoes'); if (!itens?.length) { c.append(elemento('p', 'valida', texto('nenhumErro'))); return; } for (const p of itens) { const linha = elemento('p', p.gravidade === 'erro' ? 'erro' : 'aviso', texto(p.codigo, p.argumentos)); if (p.caminho) linha.append(elemento('code', '', p.caminho)); c.append(linha); } }
  function componentes(itens, pai) { for (const c of (itens || []).slice(0, 1000)) { const caixa = elemento('div', 'componente');
    if (c.type === 'text') caixa.append(elemento('p', '', local(c.text)));
    else if (c.type === 'button') { const b = elemento('button', '', local(c.label)); b.disabled = true; caixa.append(b); caixa.append(elemento('small', 'ajuda', c.command)); }
    else if (c.type === 'field' || c.type === 'filter') { const label = elemento('label', '', local(c.label)); const input = elemento('input', 'campo'); input.value = String(c.value ?? ''); input.readOnly = true; label.append(input); caixa.append(label); }
    else if (c.type === 'list') { const ul = elemento('ul'); for (const item of c.items || []) ul.append(elemento('li', '', local(item))); caixa.append(ul); }
    else if (c.type === 'table') { const wrap = elemento('div', 'rolagem'); const tabela = elemento('table', 'tabela'); const cabecalho = elemento('tr'); for (const coluna of c.columns || []) cabecalho.append(elemento('th', '', local(coluna))); tabela.append(cabecalho); for (const linha of (c.rows || []).slice(0, 1000)) { const tr = elemento('tr'); for (const valor of linha) tr.append(elemento('td', '', valor)); tabela.append(tr); } wrap.append(tabela); caixa.append(wrap); }
    else if (c.type === 'progress') { const p = elemento('progress', 'indicador'); p.max = 1; if (Number.isFinite(c.value)) p.value = Math.max(0, Math.min(1, c.value)); p.setAttribute('aria-label', texto('duracao')); caixa.append(p); }
    else { if (c.label) caixa.append(elemento('h3', '', local(c.label))); caixa.append(elemento('pre', '', JSON.stringify(c.value ?? c.message ?? c, null, 2))); }
    pai.append(caixa);
  } }
  function grafo(fluxo) { const c = secao('fluxo'); const wrap = elemento('div', 'grafo'); const ns = 'http://www.w3.org/2000/svg'; const svg = document.createElementNS(ns, 'svg'); const nos = (fluxo.nodes || []).slice(0, 128); const edges = (fluxo.edges || []).slice(0, 256); const posicoes = new Map();
    nos.forEach((no, i) => posicoes.set(no.id, { x: 30 + i % 3 * 250, y: 30 + Math.floor(i / 3) * 130 }));
    svg.setAttribute('width', String(Math.min(3, Math.max(1, nos.length)) * 250 + 30)); svg.setAttribute('height', String(Math.max(1, Math.ceil(nos.length / 3)) * 130 + 30)); svg.setAttribute('role', 'img'); svg.setAttribute('aria-label', texto('fluxo'));
    for (const e of edges) { const a = posicoes.get(e.from); const b = posicoes.get(e.to); if (!a || !b) continue; const linha = document.createElementNS(ns, 'line'); linha.setAttribute('x1', String(a.x + 100)); linha.setAttribute('y1', String(a.y + 70)); linha.setAttribute('x2', String(b.x + 100)); linha.setAttribute('y2', String(b.y)); svg.append(linha); }
    for (const no of nos) { const p = posicoes.get(no.id); const rect = document.createElementNS(ns, 'rect'); rect.setAttribute('x', String(p.x)); rect.setAttribute('y', String(p.y)); rect.setAttribute('width', '210'); rect.setAttribute('height', '70'); rect.setAttribute('rx', '12'); svg.append(rect); const nome = document.createElementNS(ns, 'text'); nome.setAttribute('x', String(p.x + 12)); nome.setAttribute('y', String(p.y + 27)); nome.textContent = String(no.id).slice(0, 25); svg.append(nome); const tipo = document.createElementNS(ns, 'text'); tipo.setAttribute('x', String(p.x + 12)); tipo.setAttribute('y', String(p.y + 50)); tipo.textContent = String(no.kind); svg.append(tipo); }
    wrap.append(svg); c.append(wrap); for (const no of nos) json(String(no.id), no, c);
  }
  function renderizar(mensagem) { if (!app || mensagem.tipo !== 'estado') return; dicionario = mensagem.rotulos || {}; idioma = mensagem.idioma || 'pt-BR'; document.documentElement.lang = idioma; document.body.classList.toggle('catsuite', mensagem.estilo !== 'editor'); app.replaceChildren(); app.setAttribute('aria-busy', 'false');
    const estado = mensagem.estado || { modo: 'inicio', dados: {} }; const dados = estado.dados || {}; const m = dados.manifesto || dados.documento || {}; const marca = elemento('header', 'marca'); if(mensagem.recursos?.logo){const logo=elemento('img');logo.src=mensagem.recursos.logo;logo.alt=texto('logoCatSuite');logo.width=42;logo.height=42;marca.append(logo);} marca.append(elemento('strong', '', 'CatSuite Studio')); marca.append(elemento('span', 'selo', texto('versaoSdk'))); app.append(marca);
    const hero = elemento('section', 'hero'); const bloco = elemento('div'); bloco.append(elemento('p', 'sobretitulo', estado.modo === 'inicio' ? texto('desenvolvimentoPlugins') : dados.tipo || 'CATSUITE WORKSPACE')); bloco.append(elemento('h1', '', estado.modo === 'inicio' ? texto('painel') : local(m.name) || texto(estado.modo === 'previa' ? 'previa' : estado.modo === 'arquivo' ? 'arquivoAtual' : 'projetos'))); bloco.append(elemento('p', 'ajuda', estado.modo === 'inicio' ? texto('descricaoPainel') : estado.modo === 'previa' ? texto('previaAjuda') : local(m.description) || texto('restricoes'))); hero.append(bloco); const grafica = elemento('div', 'marca-grafica'); grafica.setAttribute('aria-hidden', 'true'); if(mensagem.recursos?.logo){const img=elemento('img');img.src=mensagem.recursos.logo;img.alt=texto('logoCatSuite');img.width=168;img.height=168;grafica.append(img);}else grafica.append(elemento('span','','CAT')); hero.append(grafica); app.append(hero);
    const etapas = elemento('div', 'etapas'); ['etapaCriar', 'etapaValidar', 'etapaTestar', 'etapaAssinar'].forEach((chave, i) => { const e = elemento('div', 'etapa'); e.append(elemento('b', '', '0' + (i + 1))); e.append(elemento('span', '', texto(chave))); etapas.append(e); }); app.append(etapas);
    const barra = elemento('div', 'barra'); barra.append(elemento('span', 'etiqueta', texto(mensagem.confiavel ? 'confiavelEtiqueta' : 'restritoEtiqueta'))); barra.append(elemento('span', 'etiqueta', texto(estado.modo === 'arquivo' ? 'somenteLeitura' : 'semEnvios'))); if (m.id) barra.append(elemento('code', '', m.id)); app.append(barra);
    if (dados.bloqueado) { const c = secao('protegido'); c.append(elemento('p', 'ajuda', texto('protegidoAjuda'))); c.append(botao('abrirProtegido', true)); return; }
    const acoes = elemento('div', 'acoes'); if (estado.modo !== 'arquivo') { acoes.append(botao(m.id?'abrirScript':'novoScript',true)); acoes.append(botao('criarProjeto', estado.modo === 'inicio'), botao('validarProjeto'), botao('simularProjeto'), botao('empacotarProjeto', estado.modo !== 'inicio')); if (m.id) acoes.append(botao('abrirManifesto')); } else { if(dados.tipo==='catplug') acoes.append(botao('editarPacote',true)); acoes.append(botao('copiarResultado')); if (dados.tipo !== 'catplug') acoes.append(botao('abrirCodigo')); } app.append(acoes);
    if (estado.modo === 'inicio') { const grade = elemento('div', 'grade'); [['criarProjeto','gerarDiagnostico'],['inspecionarPacote','somenteLeitura'],['aplicarEstilo','temaExplicacao']].forEach(([chave, ajuda]) => { const c = elemento('section', 'cartao'); c.append(elemento('h2', '', texto(chave)), elemento('p', 'ajuda', texto(ajuda)), botao(chave)); grade.append(c); }); app.append(grade); const ac = elemento('div','acoes'); ac.append(botao('criarFluxo'),botao('escolherIdioma'),botao('verIdentidade'),botao('abrirConfiguracoes')); app.append(ac); }
    if (m.permissions) lista('permissoes', m.permissions);
    if (m.targets) lista('destinos', m.targets.length ? m.targets : [texto('semDestino')]);
    if (dados.assinatura) { const c = secao('assinatura'); c.append(elemento('p', dados.assinatura.estado === 'valida' ? 'valida' : 'aviso', texto(dados.assinatura.estado === 'valida' ? 'assinaturaValida' : 'assinaturaAusente'))); if (dados.assinatura.impressao) { c.append(elemento('pre', '', dados.assinatura.impressao)); c.append(elemento('p', 'ajuda', texto(dados.autorReconhecido ? 'autorReconhecido' : 'autorNaoReconhecido'))); c.append(botao('copiarImpressao')); if (dados.assinatura.estado === 'valida' && !dados.autorReconhecido) c.append(botao('confiarAutor')); } }
    if (dados.problemas) problemas(dados.problemas);
    if (m.nodes) grafo(m);
    if (dados.arquivos) { const c = secao('arquivos'); for (const arquivo of dados.arquivos) json(arquivo.nome + ' · ' + arquivo.tamanho + ' B', arquivo, c); }
    if (estado.modo === 'previa' && dados.resultado) { const resultado = dados.resultado; const c = secao('previa'); c.append(elemento('p', 'avisoprivado', texto('previaAjuda'))); const grade = elemento('div', 'entradaEstado'); [['abas', resultado.abas?.length || 0], ['achados', resultado.achados?.length || 0], ['artefatos', resultado.artefatos?.length || 0], ['duracao', (resultado.duracao || 0) + ' ms']].forEach(([chave, valor]) => { const i = elemento('div'); i.append(elemento('span', 'rotulo', texto(chave)), elemento('p', 'valor', valor)); grade.append(i); }); c.append(grade); for (const aba of resultado.abas || []) { c.append(elemento('h3', '', local(aba.title))); componentes(aba.components, c); } for (const tipo of ['achados', 'artefatos', 'registros', 'request', 'response', 'mensagem', 'eventos']) if (resultado[tipo]) json(texto(tipo), resultado[tipo], c); }
    if (estado.modo === 'arquivo' && dados.tipo === 'catdata') { const c = secao('arquivos'); json(texto('copiarResultado'), m, c); }
    const rodape = elemento('footer', 'rodape'); rodape.append(elemento('p', '', texto('restricoes'))); rodape.append(botao('aplicarEstilo'),botao('aplicarIcones'),botao('escolherIdioma')); app.append(rodape);
  }
  window.addEventListener('message', evento => renderizar(evento.data)); vscode.postMessage({ tipo: 'pronto' });
  window.__renderizarCatSuite = renderizar;
})();
